### ISSUE TITLE
replay loaded

### ISSUE THREAD

**Issue by cyridotcom** [Maous-B/osu-replay-player#1]
how do you load a replay ?

**Comment by cyridotcom** [comment]
AttributeError: module 'interception' has no attribute 'key_up'
this results when enter key is pressed

**Comment by Maous-B** [comment]
> AttributeError: module 'interception' has no attribute 'key_up' this results when enter key is pressed

Make sure you download the [interception library](https://github.com/kennyhml/pyinterception) (along with the [interception driver](https://github.com/oblitum/Interception/releases/download/v1.0.1/Interception.zip)) by typing in a CMD `pip install interception-python`



> how do you load a replay ?

To load a replay, just press the "L" key and choose your .osr replay file
